openapi: 3.0.0
info:
  description: This API provides event stats
  version: "1.0.0"
  title: Health API
  contact:
    email: mdandar@bcit.ca
paths:
  /check:
    get:
      summary: Gets the heath status report
      operationId: app.get_health_check
      description: Gets general Fitness activity processsed statistics
      responses:
        '200':
          description: Successfully returned a list of fitness activity stats
          content:
            application/json:
              schema:
                type: object
                items:
                  $ref: '#/components/schemas/HealthCheck'
        '400':
          description: Invalid request
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
components:
  schemas:
    HealthCheck:
      required:
      - receiver
      - storage
      - processing
      - audit_log
      - last_update
      - calories_burned
      - last_updated
      properties:
        receiver:
          type: string
          example: Running
        storage:
          type: string
          example: Running
        processing:
          type: string
          example: Running
        audit_log:
          type: string
          example: Running
        last_update:
          type: string
          format: date-time
          example: "2022-09-29 16:35:47.001901"
      type: object